application:
  actions: actions
  hooks:
    pre-app-build: npm run build
  runtimeManifest:
    packages:
      forms:
        license: Apache-2.0
        inputs:
          ORG: aemsites
          SITE: vitamix
          LOG_LEVEL: info
          AIO_CLIENTID: $AIO_CLIENTID
          AIO_CLIENTSECRET: $AIO_CLIENTSECRET
          AIO_SCOPES: $AIO_SCOPES
          AIO_IMSORGID: $AIO_IMSORGID
          AIO_EVENTS_PROVIDER_ID: $AIO_EVENTS_PROVIDER_ID
          EMAIL_TOKEN: $EMAIL_TOKEN
        actions:
          submit:
            function: dist/actions/submit/index.js
            runtime: nodejs:22
            web: 'yes'
            annotations:
              require-adobe-auth: false
              final: true
          processor:
            function: dist/actions/processor/index.js
            runtime: nodejs:22
            limits:
              concurrency: 1
            annotations:
              final: true
          version:
            function: dist/actions/version/index.js
            runtime: nodejs:22
            web: 'yes'
            annotations:
              require-adobe-auth: false
              final: true

